In [ ]:
!pip install quandl

In [ ]:
pip install -U scikit-learn

In [ ]:
import quandl
import numpy as np

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [ ]:
df = quandl.get("WIKI/AMZN")
df.head()


Open   High    Low  Close     Volume  Ex-Dividend  Split Ratio  \
Date                                                                          
1997-05-16  22.38  23.75  20.50  20.75  1225000.0          0.0          1.0   
1997-05-19  20.50  21.25  19.50  20.50   508900.0          0.0          1.0   
1997-05-20  20.75  21.00  19.63  19.63   455600.0          0.0          1.0   
1997-05-21  19.25  19.75  16.50  17.13  1571100.0          0.0          1.0   
1997-05-22  17.25  17.38  15.75  16.75   981400.0          0.0          1.0   

            Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume  
Date                                                                 
1997-05-16   1.865000   1.979167  1.708333    1.729167   14700000.0  
1997-05-19   1.708333   1.770833  1.625000    1.708333    6106800.0  
1997-05-20   1.729167   1.750000  1.635833    1.635833    5467200.0  
1997-05-21   1.604167   1.645833  1.375000    1.427500   18853200.0  
1997-05-22   1.437500   1.448333  1.312500    1.395833   11776800.0

In [ ]:
#print(df['Open'])


In [ ]:
#df = df.reset_index()
#print(df[['Adj. Close', 'Date']])

In [ ]:
df = df[['Adj. Close']]
print(df.head())

            Adj. Close
Date                  
1997-05-16    1.729167
1997-05-19    1.708333
1997-05-20    1.635833
1997-05-21    1.427500
1997-05-22    1.395833


In [ ]:
forecast_out = 30
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)
print(df.tail())

            Adj. Close  Prediction
Date                              
2018-03-21     1581.86         NaN
2018-03-22     1544.10         NaN
2018-03-23     1495.56         NaN
2018-03-26     1555.86         NaN
2018-03-27     1497.05         NaN


<ipython-input-79-b524789328f4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)


In [ ]:
X = np.array(df.drop('Prediction', axis=1))
print(X)
X = X[:-forecast_out]
print(X)

[[   1.72916667]
 [   1.70833333]
 [   1.63583333]
 ...
 [1495.56      ]
 [1555.86      ]
 [1497.05      ]]
[[   1.72916667]
 [   1.70833333]
 [   1.63583333]
 ...
 [1350.47      ]
 [1338.99      ]
 [1386.23      ]]


In [ ]:
y = np.array(df['Prediction'])
y = y[:-forecast_out]
print(y)




[1.54166667e+00 1.51583333e+00 1.58833333e+00 ... 1.49556000e+03
 1.55586000e+03 1.49705000e+03]


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
svr_rbf = SVR(kernel= 'rbf',C=1e3,gamma= 0.1)
svr_rbf.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [ ]:
svm_confidence = svr_rbf.score(x_test,y_test)
print("svm_confidence",svm_confidence)

svm_confidence 0.9500310646225185


In [ ]:
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
lr_confidence = lr.score(x_test,y_test)
print("lr_confidence",lr_confidence)

lr_confidence 0.987057289965963


In [ ]:
x_forecast = np.array(df.drop(['Prediction'], axis=1))[-forecast_out:]
print(x_forecast)

[[1414.51]
 [1451.05]
 [1461.76]
 [1448.69]
 [1468.35]
 [1482.92]
 [1484.76]
 [1500.  ]
 [1521.95]
 [1511.98]
 [1512.45]
 [1493.45]
 [1500.25]
 [1523.61]
 [1537.64]
 [1545.  ]
 [1551.86]
 [1578.89]
 [1598.39]
 [1588.18]
 [1591.  ]
 [1582.32]
 [1571.68]
 [1544.93]
 [1586.51]
 [1581.86]
 [1544.1 ]
 [1495.56]
 [1555.86]
 [1497.05]]


In [ ]:
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[1496.98778859 1535.73381892 1547.09041402 1533.23133858 1554.07827225
 1569.52790723 1571.47899359 1587.63907849 1610.91426639 1600.34234733
 1600.84072265 1580.69363518 1587.90417175 1612.67448561 1627.55151915
 1635.35586461 1642.63002357 1671.29190643 1691.96918042 1681.14277183
 1684.13302376 1674.92898591 1663.64661692 1635.2816385  1679.37194888
 1674.44121431 1634.40152889 1582.93102226 1646.87151567 1584.51097807]


In [ ]:
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[1054.30663328  672.42062302  671.42465918  698.9283732   671.42465918
  671.42465918  671.42465918  671.42465918  671.42465918  671.42465918
  671.42465918  671.42465918  671.42465918  671.42465918  671.42465918
  671.42465918  671.42465918  671.42465918  671.42465918  671.42465918
  671.42465918  671.42465918  671.42465918  671.42465918  671.42465918
  671.42465918  671.42465918  671.42465918  671.42465918  671.42465918]
